# Generated by Django 4.2.27 on 2026-02-09 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the class or course', max_length=255)),
                ('room', models.CharField(blank=True, help_text='Room number or identifier', max_length=50)),
                ('building', models.CharField(blank=True, help_text='Building or block name', max_length=255)),
                ('latitude', models.FloatField(help_text='Classroom latitude')),
                ('longitude', models.FloatField(help_text='Classroom longitude')),
                ('radius_m', models.FloatField(default=50, help_text='Allowed radius in meters for attendance')),
                ('time_start', models.TimeField(help_text='Class start time')),
                ('time_end', models.TimeField(help_text='Class end time')),
                ('teacher', models.CharField(blank=True, help_text='Teacher name or ID', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classrooms',
            },
        ),
        migrations.CreateModel(
            name='StudentFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('matric_no', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('matric_no',)},
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_taken_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.studentface')),
            ],
            options={
                'unique_together': {('student', 'classroom', 'attendance_taken_at')},
            },
        ),
    ]
