# Generated by Django 4.2.27 on 2026-02-16 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesson', '0002_alter_classroom_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='radius_m',
            field=models.IntegerField(default=50, help_text='Allowed radius in meters'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
