# Generated by Django 4.2.27 on 2026-01-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the class or course', max_length=255)),
                ('room', models.CharField(blank=True, help_text='Room number or identifier', max_length=50)),
                ('building', models.CharField(blank=True, help_text='Building or block name', max_length=255)),
                ('latitude', models.FloatField(help_text='Classroom latitude')),
                ('longitude', models.FloatField(help_text='Classroom longitude')),
                ('radius_m', models.FloatField(default=50, help_text='Allowed radius in meters for attendance')),
                ('time_start', models.TimeField(help_text='Class start time')),
                ('time_end', models.TimeField(help_text='Class end time')),
                ('teacher', models.CharField(blank=True, help_text='Teacher name or ID', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classrooms',
            },
        ),
    ]
