# Generated by Django 4.2.27 on 2026-01-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('matric_no', models.CharField(max_length=255)),
                ('descriptor', models.JSONField()),
            ],
        ),
    ]
