# Generated by Django 4.2.27 on 2026-01-31 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_studentface'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentface',
            old_name='descriptor',
            new_name='face_encoding',
        ),
        migrations.AlterUniqueTogether(
            name='studentface',
            unique_together={('face_encoding',)},
        ),
    ]
