# Generated by Django 4.2.27 on 2026-02-05 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0003_rename_descriptor_studentface_face_encoding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_taken_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.classroom')),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.studentface')),
            ],
        ),
    ]
