# Generated by Django 4.2.27 on 2026-02-05 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0004_studentattendance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentface',
            unique_together={('matric_no',)},
        ),
        migrations.RemoveField(
            model_name='studentface',
            name='face_encoding',
        ),
    ]
