# Generated by Django 4.2.27 on 2026-02-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0005_alter_studentface_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentattendance',
            old_name='students',
            new_name='student',
        ),
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together={('student', 'classroom', 'attendance_taken_at')},
        ),
    ]
